### PR TITLE
smart-photo improvement & some bugfix

### PR DESCRIPTION
**Pull request by Lu-Biao**
1, adding multiple directory support.
2, recursive directory scanning support.
3, optimization of face recognition.
4, adding APIs
 * remove all data from the database.
 * check scan state.

```
API example:
1, add multiple directory 

curl -d '{
"method":"add_dir",
"param":"/smartphoto/mypic"
}' -H "Content-Type:application/json" -X POST [http://localhost:8080/cgi-bin/](http://localhost:8080/cgi-bin/streaming)smartphoto

curl -d '{
"method":"add_dir",
"param":"/smartphoto/photos"
}' -H "Content-Type:application/json" -X POST [http://localhost:8080/cgi-bin/](http://localhost:8080/cgi-bin/streaming)smartphoto

curl -d '{
"method":"scan_start"
}' -H "Content-Type:application/json" -X POST [http://localhost:8080/cgi-bin/](http://localhost:8080/cgi-bin/streaming)smartphoto

curl -d '{
"method":"scan_stop"
}' -H "Content-Type:application/json" -X POST [http://localhost:8080/cgi-bin/](http://localhost:8080/cgi-bin/streaming)smartphoto

2, APIs
a) delete all data from the database
curl -d '{
"method":"del_all_file"
}' -H "Content-Type:application/json" -X POST [http://localhost:8080/cgi-bin/](http://localhost:8080/cgi-bin/streaming)smartphoto

b) check scan state
curl -d '{
"method":"scan_running"
}' -H "Content-Type:application/json" -X POST [http://localhost:8080/cgi-bin/](http://localhost:8080/cgi-bin/streaming)smartphoto

curl -d '{
"method":"waiting_scan_count"
}' -H "Content-Type:application/json" -X POST [http://localhost:8080/cgi-bin/](http://localhost:8080/cgi-bin/streaming)smartphoto
```

### CODE REVIEW

**Comment by shixinlishixinli** [comment]
hi

**Comment by zliang7** [comment]
LGTM

**Comment by shixinlishixinli** [comment]
LGTM

**Comment by xwu55** [comment]
Looks good to me except too many patches for this request.

**Pull request merged**
